### ISSUE TITLE
Make @wpt-pr-bot assign someone for each RFC

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/rfcs#26]
> @web-platform-tests/wpt-core-team this RFC is two weeks old now, we should decide what to do or what additional information is needed. Nobody is ultimately responsible for this process working, so perhaps we should assign someone as the responsible person for each RFC? Any volunteers?

_Originally posted by @foolip in https://github.com/web-platform-tests/rfcs/pull/25#issuecomment-523483038_

> perhaps we should assign someone as the responsible person for each RFC?

I think that would be good. This seems similar to reviews of wpt PRs. For that, we made @wpt-pr-bot assign a single person for each PR. I suggest that can be done in this repo as well, if the bot knows who are in the core team.

Benefits:
- A single person responsible for each RFC hopefully shortens the time to resolution for RFCs overall.
- More transparency if a core team member is being non-responsive.

**Comment by zcorpan** [comment]
I'm not sure anymore this is a good idea. The volume here is very low, it makes more sense to have us manually try to assign each PR.

**Comment by stephenmcgruer** [comment]
I agree. I have concerns about the outstanding RFCs, but I don't think a bot is going to help solve those cases :). I'm going to close this; if anyone disagrees then please feel free to reopen with your thoughts :).
