### ISSUE TITLE
Create an RFC for what material is and is not allowed in WPT

### ISSUE THREAD

**Issue by boazsender** [web-platform-tests/rfcs#30]
We lack a clear policy of when to accept/reject material.

Some further action is needed after the discussion at TPAC regarding "tests that depend on test-only APIs implemented using Mojo for Chromium, e.g. [WebXR](https://github.com/immersive-web/webxr-test-api/blob/master/explainer.md), [WebUSB](https://wicg.github.io/webusb/test/)".

It seems like there was latent consensus that tests which can only be run in one browser engine and will never be able to run in multiple engines, should not be included in WPT. There was even linting recently written to address a case of this: https://github.com/web-platform-tests/wpt/pull/18509.

**Comment by Hexcles** [comment]
Tangentially, we also discussed the possibility of "tentative" directories and correspondingly a guidance like e.g. "a directory for a new API with only an explainer without a draft spec should be marked as tentative". I'm not sure if we should have a different RFC for "tentative" directories though cc @jgraham .

**Comment by foolip** [comment]
@boazsender can I assign this to you? I don't think @web-platform-tests/wpt-core-team feel we are on the hook to resolve issues in this repo, just PRs.

**Comment by Hexcles** [comment]
Also in regards to the specifics of MojoJS: https://github.com/web-platform-tests/wpt/issues/16455#issuecomment-532040838

**Comment by boazsender** [comment]
@foolip: sure thing!

**Comment by foolip** [comment]
@boazsender I'm going to go ahead and close this issue now, but if you do still want to send an RFC for it, certainly that would be welcome!
