### ISSUE TITLE
Promise of engaging in reprisal by WPT adminsitrative agent against revoked Member for exercising Free Speech; Appeal of WPT membership revocation and ban for no articulatable reason; Double Jeopardy; Due Process; Recource and Remedy

### ISSUE THREAD

**Issue by guest271314** [web-platform-tests/rfcs#55]
This repository clearly makes requests for comment and wider review

> This RFC (request for comments) process is used to request wider review.

Postetd the expert opinion that was requested here https://github.com/web-platform-tests/rfcs/issues/21#issuecomment-619993348.

> Due to your recent conduct in web-platform-tests, you are being temporarily excluded from web-platform-tests project spaces for the period of 1 month. This exclusion includes all repositories under the web-platform-tests GitHub organization, the #testing channel on irc.w3.org, and the public-test-infra@w3.org mailing list.

From Moderation notice: web-platform-tests Simon Pieters

>   [Your comment](https://github.com/web-platform-tests/rfcs/issues/21#issuecomment-619993348) in the RFC issue was found to be unacceptable: specifically your ad-hominem attacks on specific community members and your comparison of the general community to the Gestapo. Disagreeing with an RFC or technical issue is welcome, but verbally attacking members of the community or the community in general is not.

> After 1 month, the ban will be lifted. Future incidents of the above-described behavior or other behavior deemed not to meet our standards for participation will result in a permanent exclusion, as will any attempt to argue against this temporary ban in public or private communication channels.

> We note that you had sent an appeal, without knowing the rationale for the ban. Let us know whether you would like to withdraw the appeal.

You need to state _precisely_ the reason for deprivation of right or privilege, the Liberty Interest that WPT created by assigning Membership and deprived thereof for a vauge reason. A link to a comment is not an articulated reason. What is the _specific_ allegation? What _specific_ words is WPT arbitrarily assigning a value to whereby a decision is made to deprive a member of a privilege or right, indeed membership in the Organization itself, summarily, _and_ a 30-day ban, which is Double Jeopardy?

WPT invented an alleged reason for the Membership revocation and 30-day ban, ex post fact, which means, in lay terms, _after the fact_ - only after asking for the reason in the NOTICE OF APPEAL that filed. 

"Gestapo" is not a banned word. There is no such thing as banned words in a free society. 

Telling an individual they don't get it,  and probably never will, is not an attack. That is direct communication. So far, that assessment is true and correct. Given was banned for exactly printing the word "Gestapo". It is not clear what "attack" is intended to mean. 

Should users provide a list of words that will offend them when they first reply to a differnt user?

There is no such thing as "respect". That is an emotion that changes at the whim of the human mind. 

You need to be capable of handling direct feedback from individuals that might not speak the exact same language or dialect as you, or might not suffer from _your_ current emotional state, where you take offense to certain words. 

Well, the entire English language is an _equivocal language_, meaning the same word _spelled_ the same way can _invoke_ different meanings depending on knowledge of the language. 

You should really not be so sensitive. 

Some Elementary Comments on The Rights of Freedom of Expression Noam Chomsky
Appeared as a Preface to Robert Faurisson, Mémoire en défense, October 11, 1980 https://chomsky.info/19801011/
> Let me add a final remark about Faurisson’s alleged “anti-Semitism.” Note first that even if Faurisson were to be a rabid anti-Semite and fanatic pro-Nazi — such charges have been presented to me in private correspondence that it would be improper to cite in detail here — this would have no bearing whatsoever on the legitimacy of the defense of his civil rights. On the contrary, it would make it all the more imperative to defend them since, once again, it has been a truism for years, indeed centuries, that it is precisely in the case of horrendous ideas that the right of free expression must be most vigorously defended; it is easy enough to defend free expression for those who require no such defense.

**WPT has NOT officially responded to the NOTICE OF APPEAL**. 

When WPT has no appeals process, and not even bothered to mention the term "appeal" though has actually had discussions on the matter and filed a PR for "CoC Enforcement Team" the cart is before the horse, and yes, that _is_ Gestapo behaviour, individuals sitting in Gulags for years without any Recourse or Remedy, without any appeal process in place. That was by design. Here, the case appears to be ignorance of fundamental administrative procedure, lack of experience appealing anything of significance, whether private or public, and still perhaps overestimating a parent organization that also has administrative issues, and perhaps thinking that you are the smartest people in the room. 

You  obviously are not the smartest people in the room if you go through all of the formalities of settiing up a "Code of Coduct Enforcement Team" that can only be right 100% of the time because no appeal process was even considered to be put in place to review, for example, the case of when a    user appeals that adverse action, instead WPT actually asked to _withdraw_ the appeal. That is extraordinary. 

To settle a dispute one party may Offer, and Consideration, Acceptance might follow. 

Here, WPT offerered nothing of _value_ when asking if wanted to withdraw appeal. 

Since am appealing the original action, why would Acceptance of a Consideration with having no inherent value be made? Why withdraw the appeal? What is WPT offering to create a Remedy? Nothing. No response. Do not pretend like you have a "CoC Enforcement Team" if you have no administrative appeals process in place, transparent and published, for when, by act or omission, "CoC Enforcement Team" - and Administrative Head of "CoC Enforcement Team" is wrong.

If you make an Offer at least attach a value to that offer. To state one communication is "unacceptable" yet to on the other hand make an offer to settle for a Consideration with no value e.g., "withdraw the appeal and WPT will reinstate membership and rescind 30-day ban", is a thing of value, that is an "unacceptable" Offer. No Remedy is being Offered, only ststus quo. 

Not only did the user that directly communicate with not get the point was making at the time, WPT management did not get it, and still does not get it, as WPT has completely failed to Reply to a duly filed NOTICE OF APPEAL, which is an internationally understood language. As if the user would not notice that the request was made becuase WPT has no appeal process in place, a clear violation  of any semblance of Due Process.

Twitter actually asked this user to send a scanned copy of government-issued ID to unsuspend account there, where, again, was suspended for no reason.

> - a signed request that includes your username (e.g., @guest271314 or twitter.com/guest271314) and the email address associated with your Twitter account; 
> - the specific information you are requesting (e.g.: IP logs); and
> - a scanned copy of your valid, government-issued photo ID

After asked if an actual human was fielding the appeal have not had any reply. Twitter is acting as a government agent and, or has a series of bots rolling around with no human  involved.

Do not go down that road. The algorithm did not do it. An emotional human that does  not understand any languages other than the one they  speak did it.

There is no such thing as  an  "offensive" word in the English language. That is based on the interpretation of the reader or listener. It's in _their_ head.  Presumption of being "attacked" does not mean you are being attacked. Warnings to _not_ become a Gestapo are fact merited this case, where the results borne out prove WPT has no appeal process, and has not even thought of the implications of not officially creating an appeals process to contest adverse actions taken by WPT. An organization that does not have  an appeals process can hardly be compared to a modern organization that has oversight,  and where the conduct of the Administrative Head and Management can be challenged directly - without promise of reprisal.

One or more undisclosed WPT administration agent summarily revoked membership in WPT for no articulated reason. That is the same as claiming a test is not working though failing to state how the test  is not working, on what line the error  or exception occurs. 

The correct reply to those comments, or any comments that _you_ request

"Thank you for sharing. WPT will consider your feedback moving forwards."

Not to revoke membership in WPT without cause, and without recourse. 

Immediately appealed the vague claim of an "attack" on a user for providing expert opinion that  has borne out here by exposing the fact that WPT has absolutely no administrative appeals process in place, meaning the action by WPT agents was  arbitrary and capricious, providing no means to exercise Recourse for the purpose of creating a Rememdy to the erroneous membership revocation and ban.

There was no "attack". That is  an absurb exaggeration of the direct communication by an expert on the matter of fraudulent bans imposed by organizations. You got what you asked for. And still failed to even get sharing a clue as to what you might be missing in _your_discussions. Perhaps becuase none of WPT agents have had to fight appeals for years, thus until they experience an incorrect medical bill, dealing with insurance, or some other minor experience where they _might_ recall this subject will they understand the import of a transparent and fair _process_, Due Process.  But, you still might think that you  are the smartest people in the room. Maybe in Python, obviously not in administrative procedure, because WPT actually suggests in open discussion that no process might be needed, yet this user gets banned for stating you don't get it and probably never will.  You just might not, even when you are faced with some occupational, municipal, commercial, or other "appeal", meaning you give NOTICE that you need a Remedy for the specific deprivation articulated. You banned, but you still _have not_ said _why_.

Was asked to withdraw the NOTICE OF APPEAL because WPT  is operating without even a basic, transparent,  and just appeal process in place.

Double Jeopardy means being punished twice for the same action. There was no reason given for the WPT membership revocation. The vague reason for the 30-day ban from contributing to WPT must stem from the same origin, meaning was punished twice

There was no "attack" whatsoever. Warned WPT to make sure to not go down the path of arbitrary and capricious actions that amount to a totalitarian top-down heirarchal regime accountable to no one, because there is no means in place to appeal the decisions made, which is a glaring violation of Fundamental Liberty Interest under the U.S., under Amendment 14 to the Constitution of the United States, which is the Supreme Law of the Land, for failing to implement an administrative appeal process for individuals who have been deprived of a right or privilege to seek Recourse in order to create a Remedy to make them whole again, specifically Substantive and Procedural Due Process; in this case WPT violates both by not having an appeals process at all, a glaring omission. WPT has no way to review its actions. Or, has decided to expressly _not_ operate in kind with, in general, all administrative agencies or organizations, that is, to have a means for appealing adverse actions, in a transparent and clearly defined official process. 

WPT failing to have an appeals process means when a user appeals adverse action made by "CoC Enforcement Team" there is no way to know when the appeal has been exhausted, because there is no official first step, and this comment https://github.com/web-platform-tests/rfcs/issues/21#issuecomment-621261853

> I don't think we really need to define a process here?

provides illumination onto the fact that WPT apparently hastily, or worse, ignorantly, attempting to pass along boilerplate charter "CoC Enforcement Team" that is prima facie lacking the term "appeal" is not found in the primary source documents relating thereto https://github.com/web-platform-tests/rfcs/pull/54, meaning no Recourse and no Remedy, which is a rare omission in  any formal organization, whether public, private, or cooperative. There MUST be a means to directly challenge official action else WPT acts as a tyranny.

That is exactly what was warning WPT against doing in the comments, WPT did so anyway and in doing so reveals that the state of affairs is worse than estimated could occur: WPT just do not get the importance of Procedural Due Process, adminsistrative Recourse and Remedy and exhaustion, for the ability to sue to a higher body once WPT, or any formal entity officially states their appeal is final, becuase WPT did not mention appeal once in their official documents. That is a problem. That means WPT "CoC Enforcement Team" is always right, by fiat, and there can never be any decision by WPT "CoC Enforcement Team" that is wrong, because WPT has predetermined that no appeals exist, and thus even when WPT is wrong, WPT is always right, again,  which warned against.

The most egregious part of the official response from WPT - which as an organization still has failed to submit a Response to the NOTICE OF APPEAL filed - is that WPT administrative agent promised reprisal for discussing WPT errors, omissions, failures, and frankly, violations of basic tenets of adminsitrative procedure (guranteed under the Due Process Clause of the Const. of U.S., one territory where GitHub operates) in this matter. 

The author of the post has the audacity to mention "unacceptable" while actually making the official promise to engage in the reprisal of banning contribution to WPT permanently for discussing the APPEAL filed in public or private. That is outlandish, and the prime example of hypocritical conduct that warned WPT from engaging in. 

Am not impressed with WPT actions and response in this matter. Like the Wizard of Oz. However, that is not the reason for this issue. 

If you are really going to support an administrative agent promise reprisal for exercise of Free Speech, for Appealing the vague, double-jeopardy sanctions imposed on this user, then make that clear here and now so can be certain whatever imaginary appeal system that WPT does not actually have is exhausted and can remove all esteem from association with your organization. 

**Remedy**

You cannot give back 30 days. You do not have  that power. You can reinstate Membership in WPT, though at this point it would only be for the purpose of being made whole again, any value that was attached was dissolved when the Double Jeopardy ban-revocation occurred, the absurd request to withdraw the appeal followed by promise of reprisal. Whether your moral integrity is up to par or not will be made unequivocally clear, right here.

**Comment by burg** [comment]
Modest proposal: post patches related to WPT, or shut up and go away. Nobody has time to read your wall of text.

**Comment by tabatkins** [comment]
@burg Being rude in response is not appropriate. This issue will be dealt with by the WPT moderators.

**Comment by guest271314** [comment]
@tabatkins No worries. Have no concept of "rude", either way. Nonetheless illustrates the notion of attempting to arbitrarily define what printed text in a post, on any platform, anywhere, is "rude" or "offensive", "disrespectful", et al., and the exceptions granted for some, perhaps not others, such a "rule", acts or omissions are basically impossible to implement without nullifying Free Speech. 

@burg Then the text is not for you. You cannot possibly speak for "nobody". You can only speak for yourself. Your corporation pays lawyers to read text so the smartest people in the room can be witty and lazy at the same time.

**Comment by guest271314** [comment]
@burg 

> Nobody has time to read your wall of text.

Therein lies a source of endless problems. Following that logic "nobody" has the time to read any "End User Agreement" or "Terms of Use", or for that matter "Code of Conduct", any Rule or Law, or the organic Constitution for the United States of America, either. Some public schools do not teach pupils cursive anymore, so if they happen to attempt to read the Constitution they might not have been taught how to. That "wall of text" that you refer to is nominal. Try reading expenditures for the entire Senate, or Scott v. Sandford, (19 How.) 393 (1857), an excerpt from Chief Justice Taney's opinion, the published case is well over 100 pages 

> The words "people of the United States" and "citizens" are synonymous terms, and mean the same thing. They both describe the political body who, according to our republican institutions, form the sovereignty and who hold the power and conduct the Government through their representatives. They are what we familiarly call the "sovereign people," and every citizen is one of this people, and a constituent member of this sovereignty. The question before us is whether the class of persons described in the plea in abatement compose a portion of this people, and are constituent members of this sovereignty? We think they are not, and that they are not included, and were not intended to be included, under the word "citizens" in the Constitution, and can therefore claim none of the rights and privileges which that instrument provides for and secures to citizens of the United States. On the contrary, they were at that time considered as a subordinate

> Page 60 U. S. 405

> and inferior class of beings who had been subjugated by the dominant race, and, whether emancipated or not, yet remained subject to their authority, and had no rights or privileges but such as those who held the power and the Government might choose to grant them.

That "wall of text", again, is trivial. Try litigating to SCOTUS, twice, over the course of 4 years, by yourself.
