### ISSUE TITLE
Propose RFCs as issues

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/rfcs#9]
# Summary
Propose RFCs as PRs rather than issues

# Motivation
See https://github.com/web-platform-tests/rfcs/pull/8 for other sections.

**Comment by foolip** [comment]
I support this!

**Comment by foolip** [comment]
@jgraham 7 days have passed, so if you want to declare this accepted and merge https://github.com/web-platform-tests/rfcs/pull/8 that'd be OK. Do you want to update README.md in the same PR?

**Comment by jgraham** [comment]
I'll do the README changes as a non-RFC PR.
